name: color
version: 3.0.0
description: A simple Dart package exposing a Color class which can be used to create, convert, alter, and compare colors in a variety of colorspaces.

authors:
- Michael Fenwick <mike@mikefenwick.com>

homepage: https://github.com/MichaelFenwick/Color

environment:
  sdk: '>=2.12.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.6.2
  build_web_compilers: ^2.12.0
  pedantic: ^1.11.0
  test: ^1.16.5
